import type { ru } from "./ru.js";

export const en: Record<keyof typeof ru, string> = {
  access_denied: "This bot is private. Ask the owner for a personal invitation link.",
  access_denied_toast: "No access",
  private_only: "I only work in private chats: everyone has their own separate task list there.",
  invite_invalid: "This invitation link is invalid, expired, or has already been used.",
  invite_already_registered: "You already have an account in this bot; no link needed. If the bot does not answer, contact the owner.",
  invite_created: "Send this personal link to a new user:\n{link}\n\nIt works once for {days} days. They will get a separate workspace and will not see your data.",
  invite_not_allowed: "Only the project owner can create invitation links.",
  invite_failed: "Could not create an invitation link. Please try again later.",
  settings_missing: "Account settings were not found. Send /start to create them again.",
  unsupported_message: "For now I understand only text and voice messages. Describe what you need in words, for example: “meeting on Thursday at 16:00”.",

  status_server: "✅ IPsycho server is up",
  status_db_ok: "✅ PostgreSQL responds",
  status_db_failed: "❌ PostgreSQL does not respond",
  status_telegram: "✅ Telegram delivered this reply",
  status_ai_configured: "🤖 AI: configured ({provider})",
  status_ai_missing: "🤖 AI: not configured",
  status_ai_suspended: "🤖 AI: suspended for this account",
  status_deliveries: "🔔 Reminders queued: {pending}",
  status_deliveries_ambiguous: "⚠️ Deliveries with unknown outcome: {ambiguous}",

  history_cleared: "AI history cleared ({count} messages). Telegram messages, tasks, goals, reminders, and settings are unchanged.",
  history_cleared_toast: "AI history cleared ({count})",
  cancel_done: "Current input and review stopped. Tasks and decisions already saved are unchanged.",

  delete_prompt:
    "Deletion stops AI, briefings and reminders immediately. Data is removed for good after {days} days; until then the account can be restored with /restore. Residual data may remain in encrypted backups: {daily} daily and {weekly} weekly copies.",
  delete_confirm_button: "Confirm deletion",
  delete_scheduled_toast: "Deletion scheduled",
  delete_scheduled: "The account is locked. It can be restored with /restore within {days} days.",
  delete_failed_toast: "Could not schedule deletion",
  delete_unavailable_toast: "The account is no longer available",
  restore_done: "The account is restored. Future reminders are active again.",
  restore_unavailable: "The account is not awaiting deletion, or the restore period has passed.",
  ai_revoked: "Consent for external AI processing is revoked. Reminders, briefings and buttons keep working.",
  retry_failed: "The retry did not succeed yet. The message is saved.",

  consent_prompt:
    "For AI chat, message text will be sent to the external provider {provider}. With OpenAI, voice messages are sent only for transcription and are not stored as audio. Allow this processing?",
  consent_yes_button: "I agree",
  consent_no_button: "Not now",
  consent_granted_toast: "Consent saved",
  consent_granted_replaying: "Done, processing your last message.",
  consent_granted: "Done. Tell me what to do.",
  consent_declined_toast: "AI not enabled",
  consent_declined: "All right, AI stays off. Buttons, reminders and briefings keep working; I will not process free text. Enable it any time by simply writing to me again.",
  voice_consent_prompt:
    "For AI processing, text is sent to the external provider, and voice goes to OpenAI only for transcription. Audio is not stored; the recognised text is processed and kept like an ordinary message. Allow?",
  voice_consent_granted: "Voice input is on. Send the voice message again: audio is not resent automatically.",
  voice_consent_declined_toast: "Voice input not enabled",

  chat_nothing_to_retry: "There are no saved messages waiting for AI processing.",
  chat_ai_suspended: "AI processing is suspended for this account. Reminders and buttons keep working.",
  chat_ai_unavailable: "AI is unavailable right now. Your message is saved: send /retry_ai whenever you want to retry. Reminders and buttons keep working.",
  chat_rate_limited: "The hourly AI limit is reached ({limit} messages). I can read text again after {until}. Buttons, reminders and briefings work as usual.",
  text_failed: "Could not process the message. Nothing changed; I will try again myself.",
  ai_retry_exhausted: "I still could not process the message: \u201c{preview}\u201d. Nothing changed. Try again: /retry_ai",
  text_uncertain: "I am not sure whether the change was saved. Do not repeat it yet: I will check and tell you. Open the list: /today",
  end_done: "Conversation ended. Everything already saved stays.",
  end_none: "There is no active review right now.",
  until_morning: "All right. Quiet until {until}.",

  timezone_usage: "Send a city or a timezone. For example: /timezone Berlin or /timezone Europe/Berlin",
  timezone_set: "Main timezone: {timezone}. Existing tasks are not shifted. Briefings and quiet hours still use the previous zone: apply the new one to them too?",
  timezone_invalid: "I do not know that timezone. Send a city, for example “Berlin”, or a zone like Europe/Berlin.",
  tz_apply_digests: "To briefings",
  tz_apply_quiet: "To quiet hours",
  tz_apply_both: "To both",
  tz_keep: "Keep as is",
  tz_applied_toast: "Timezone applied",
  language_auto: "The interface language follows Telegram again.",
  language_set: "Interface language pinned: {language}. AI still replies in the language of the current message.",
  language_usage: "Format: /language auto, /language ru, /language uk or /language en",
  digest_usage: "Briefing now: /{kind}\nEnable: /{kind} on HH:MM\nDisable: /{kind} off",
  digest_on_morning: "Morning briefing enabled.",
  digest_off: "Briefing disabled.",
  time_invalid: "Invalid time. Use HH:MM, for example 09:30.",
  weekly_usage: "Week card now: /weekly\nWeek plan: /week\nEnable: /weekly on <day 1-7> <HH:MM>\nDisable: /weekly off",
  weekly_on: "The week card is on.",
  weekly_off: "The week card is off.",
  weekly_invalid: "Could not change the setting. Check the weekday (1–7) and the time HH:MM.",
  quiet_default: "Quiet hours: weekdays 22:00–08:00, weekends 23:00–09:00.",
  quiet_off: "Quiet hours disabled.",
  quiet_updated: "Quiet hours updated.",
  quiet_usage: "Format: /quiet default, /quiet off or /quiet 22:00 08:00 23:00 09:00",
  snooze_off: "Temporary silence is off.",
  snooze_until: "Quiet until {until}.",
  snooze_usage: "Format: /snooze morning, /snooze off or /snooze <minutes 15..10080>",
  snooze_failed: "Could not change temporary silence.",
  rd_event: "Default event reminders updated.{warning}",
  rd_event_warning: " Many reminders, or some closer than 15 minutes: contacts that close will be merged.",
  rd_task: "Default reminder for planned tasks updated.",
  rd_critical: "Critical escalation interval updated.",
  rd_usage: "Examples: /reminder_defaults seen 60 30 15; event -60,-15,0; task 0; critical 60",
  rd_failed: "Could not change the setting. Check the numbers and the command format.",

  onb_timezone_prompt: "What is your timezone? Briefing times and phrases like “tomorrow at 10” depend on it. Send a city, for example “Berlin”, or pick one below.",
  onb_timezone_other: "Other",
  onb_timezone_saved_toast: "Timezone saved",

  bad_command_toast: "Invalid command",
  saved_toast: "Saved",
  done_toast: "Done",
  back_button: "← Back",
  not_now_button: "✖️ Not now",
  today_button: "☀️ Today",
  tasks_button: "📋 All tasks",
  to_tasks_button: "← To tasks",
  settings_button: "⚙️ Settings",
  reminders_button: "🔔 Reminders",
  goals_button: "🎯 Goals",
  help_button: "📖 How it works",

  tasks_header: "📋 Tasks · {scope} ({count})",
  tasks_scope_empty: "Nothing in this filter.",
  tasks_hint: "To change, complete, or reschedule a task, just write it in a message.",
  scope_overdue: "overdue",
  scope_today: "today",
  scope_week: "week",
  scope_month: "month",
  scope_all: "all",
  scope_nodate: "no date",
  scope_overdue_button: "⚠️ {count}",
  scope_today_button: "Today",
  scope_week_button: "Week",
  scope_month_button: "Month",
  scope_all_button: "All",
  scope_nodate_button: "🫧 No date",
  paused_series_button: "⏸ Paused: {count}",
  week_plan_header: "🗂 Week plan from {monday} · in the pool: {count}",
  week_plan_summary: "Closed last week: {done}. Taken and not started: {stale}.",
  week_plan_hint: "Tap a task to take it for the week or put it back in the pool.",
  week_plan_empty: "The pool has no undated tasks. Describe one in your own words and it shows up here.",
  week_plan_button: "🗂 Week",
  week_picked_toast: "Taken for this week",
  week_released_toast: "Back in the pool",
  week_full_toast: "This week already holds {limit} tasks. Put one back to add another.",
  week_pick_gone_toast: "That task is no longer in the pool",
  week_take_today_toast: "Set for today",
  week_take_today_row: "▶️ Today: {title}",
  week_take_today_failed_toast: "Could not set it for today",
  resume_series_button: "▶️ {title}",
  paused_series_header: "⏸ Paused series: {count}",
  paused_series_empty: "No series is paused.",
  series_resumed: "The series runs again",
  group_next: "next",
  group_open_hint: "Lines with ▸ expand: they hold several dates.",
  page_next_button: "{count} more →",
  page_prev_button: "← Previous",
  label_main: "Main",
  nothing_planned: "Nothing is planned.",
  list_more: "+ {count} more",
  briefing_morning_title: "☀️ Today",
  briefing_weekly_title: "🗂 Week plan",
  briefing_taken_week: "Taken this week:",
  briefing_week_cta: "Open the week plan: /week",
  briefing_pool_empty: "The pool has no undated tasks.",
  today_stale: "⚠️ Overdue from before: {count}",
  today_stale_button: "⚠️ Overdue ({count})",
  list_changed_toast: "The list changed, refreshed it",
  guide_back_button: "← Help",

  prefs_snooze_toast: "Quiet until morning",
  prefs_failed_toast: "Could not change the setting",
  prefs_morning_on: "☀️ Morning: on",
  prefs_morning_off: "☀️ Morning: off",
  prefs_weekly_on: "📅 Week: on",
  prefs_weekly_off: "📅 Week: off",
  prefs_quiet_on: "🔕 Quiet hours: on",
  prefs_quiet_off: "🔕 Quiet hours: off",
  prefs_snooze_morning: "🔕 Until morning",
  prefs_context: "🧭 Context",
  prefs_clear_history: "🧠 Clear AI history",

  reminders_title: "🔔 Upcoming reminders",
  reminders_none: "🔔 Reminders\n\nNo upcoming reminders.",
  reminders_hint: "Tap a reminder to cancel it. To move one, just write a message.",
  reminders_day_today: "Today",
  reminders_day_tomorrow: "Tomorrow",
  goals_header: "🎯 Goals · {scope} ({count})",
  goals_scope_active: "active",
  goals_scope_paused: "paused",
  goals_scope_completed: "completed",
  goals_scope_active_button: "Active",
  goals_scope_paused_button: "Paused",
  goals_scope_completed_button: "Completed",
  goals_empty_scope: "No goals in this filter.",
  goals_no_tasks: "no linked active tasks",
  goals_hint: "To edit a goal or link a task, just write it in a message.",
  goal_why: "Why",
  goal_deadline: "by {date}",
  settings_section_time: "Time and language",
  settings_section_digests: "Briefings",
  settings_section_quiet: "Quiet hours and data",
  settings_timezone_button: "🌍 Timezone",
  settings_language_button: "🗣 Language",
  settings_language_prompt: "Which interface language should I use?",
  settings_language_auto_button: "Same as Telegram",
  reminder_cancel_button: "✖ {title} · {when}",
  reminder_cancelled_toast: "Reminder cancelled",
  reminder_already_toast: "It was already sent or cancelled",
  reminder_cancel_failed_toast: "Could not cancel the reminder",

  confirm_button: "Confirm",
  decline_button: "No, thanks",
  undo_button: "↩️ Put it back",
  undo_reschedule_button: "↩️ Undo the move",
  confirm_toast: "Confirmed ✓",
  confirm_toast_many: "Confirmed: {count}",
  confirmed_text: "Confirmed.",
  declined_toast: "Dropped",
  already_handled_toast: "Already handled",
  undo_toast: "Put back as it was",
  undo_text: "↩️ Put back as it was. The change is undone:",
  action_stale_toast: "Can no longer be undone: more than a day passed or the task changed since",
  action_uncertain_toast: "Not sure it was saved. I will check and tell you",
  action_done_undo_hint: "Can be undone within a day.",

  task_not_found_toast: "Task not found",
  task_unavailable_toast: "The task is no longer available",
  state_changed_toast: "The state already changed or the action is unavailable",
  resched_prompt_toast: "When to come back?",
  cancel_what_toast: "Cancel what?",
  cancel_one_button: "Only this one",
  cancel_series_button: "The whole series",
  done_occurrence_toast: "Done ✓",
  skipped_toast: "Skipped",
  cancelled_occurrence_toast: "Cancelled",
  reschedule_button: "🕒 Reschedule",
  cancel_task_button: "❌ Cancel",

  resched_custom_toast: "Send the new time",
  resched_prompt: "Write when: {hint}. You can add a reason in the same message.",
  resched_hint_window: "for example “tomorrow 10:00–11:00”",
  resched_hint_deadline: "for example “by Friday” or “by 12.09 18:00”",
  resched_hint_point: "for example “tomorrow at 10” or “Mon 9:30”",
  reason_toast: "Why are you moving it?",
  reason_prompt_text: "🕒 {title}\n\nWhy are you moving it? Write briefly in one message.",
  reason_write_toast: "Write the reason",
  rescheduled_toast: "Moved",
  rescheduled_text: "Moved.",
  rescheduled_fuzzy_text: "Returned the task to loose planning.",
  resched_failed_toast: "Could not move it",
  resched_failed_text: "Could not move it. Say the new time again, for example “tomorrow at 10” or “Fri 15:00–16:00”.",
  reason_too_short: "Could not move it. Write briefly why you are moving it, once more.",
  repeated_reschedule: "This is a repeated move. If the problem is not only the time, you can record what is stopping you from starting.",

  followup_failed_toast: "Could not change the check",
  snooze_reminder_toast: "I will remind you later",
  snooze_15m_button: "⏰ In 15 min",
  snooze_1h_button: "⏰ In an hour",

  series_paused: "Series paused",
  series_cancelled: "Series cancelled",
  series_not_found_toast: "Series not found",
  series_changed_toast: "The series has already changed",

  quiet_deferred_notice: "🔕 Was in quiet hours, showing it now",
  escalation_header: "🔴 Past the deadline — reminder #{n}",
  mute_escalation_button: "🔕 Enough for this task",
  mute_escalation_toast: "No more reminders for this task",

  voice_suspended: "AI processing is suspended for this account. Voice input is unavailable.",
  ai_spend_warning: "Heads-up: estimated AI spend this month reached ${amount}. This is only a notice; AI is not switched off automatically.",
  ai_spend_owner_notice: "IPsycho: user {userId} reached the AI spend warning of ${amount}.",
  ops_alert: "IPsycho: the reminder queue needs attention. {details}",
  voice_too_long: "The voice message is too long or too large. Send a recording up to {minutes} min and {mb} MB, or text.",
  voice_openai_only: "Voice input is available only with OpenAI configured.",
  voice_rate_limited: "The hourly AI limit is reached. Try later; buttons and reminders keep working.",
  voice_recognizing: "🎙 Transcribing…",
  voice_consent_needed: "AI processing needs your consent.",
  voice_unavailable: "Voice input is unavailable right now.",
  voice_unrecognized: "Could not recognise the speech. Try a shorter recording or send text.",
  voice_failed: "Could not process the voice message. Try sending a shorter one or write text.",
};
