import type { ru } from "./ru.js";

export const en: Record<keyof typeof ru, string> = {
  access_denied: "This bot is private. Ask the owner for a personal invitation link.",
  access_denied_toast: "No access",
  private_only: "I only work in private chats: everyone has their own separate task list there.",
  invite_invalid: "This invitation link is invalid, expired, or has already been used.",
  invite_already_registered: "You already have an account in this bot; no link needed. If the bot does not answer, contact the owner.",
  invite_created: "Send this personal link to a new user:\n{link}\n\nIt works once for {days} days. They will get a separate workspace and will not see your data.",
  invite_not_allowed: "Only the project owner can create invitation links.",
  invite_failed: "Could not create an invitation link. Please try again later.",
  settings_missing: "Account settings were not found. Send /start to create them again.",
  unsupported_message: "For now I understand only text and voice messages. Describe what you need in words, for example: “meeting on Thursday at 16:00”.",

  status_server: "✅ IPsycho server is up",
  status_db_ok: "✅ PostgreSQL responds",
  status_db_failed: "❌ PostgreSQL does not respond",
  status_telegram: "✅ Telegram delivered this reply",
  status_ai_configured: "🤖 AI: configured ({provider})",
  status_ai_missing: "🤖 AI: not configured",
  status_ai_suspended: "🤖 AI: suspended for this account",
  status_deliveries: "🔔 Reminders queued: {pending}",
  status_deliveries_ambiguous: "⚠️ Deliveries with unknown outcome: {ambiguous}",

  history_cleared: "AI history cleared ({count} messages). Telegram messages, tasks, goals, reminders, and settings are unchanged.",
  cancel_done: "Current input and review stopped. Tasks and decisions already saved are unchanged.",

  delete_prompt:
    "Deletion stops AI, briefings and reminders immediately. Data is removed for good after {days} days; until then the account can be restored with /restore. Residual data may remain in encrypted backups: {daily} daily and {weekly} weekly copies.",
  delete_confirm_button: "Confirm deletion",
  delete_scheduled_toast: "Deletion scheduled",
  delete_scheduled: "The account is locked. It can be restored with /restore within {days} days.",
  delete_failed_toast: "Could not schedule deletion",
  deletion_pending_notice: "The account is awaiting deletion, so everything is stopped. You can still bring it back for {days} more days: /restore",
  deletion_pending_toast: "The account is awaiting deletion. Bring it back: /restore",
  restore_done: "The account is restored. Future reminders are active again.",
  restore_unavailable: "The account is not awaiting deletion, or the restore period has passed.",
  ai_revoked: "Consent for external AI processing is revoked. Reminders, briefings and buttons keep working.",
  retry_failed: "The retry did not succeed yet. The message is saved.",

  consent_prompt:
    "For AI chat, message text will be sent to the external provider {provider}. With OpenAI, voice messages are sent only for transcription and are not stored as audio. Allow this processing?",
  consent_yes_button: "I agree",
  consent_no_button: "Not now",
  consent_granted_toast: "Consent saved",
  consent_granted_replaying: "Done, processing your last message.",
  consent_granted: "Done. Tell me what to do.",
  consent_declined_toast: "AI not enabled",
  consent_declined: "All right, AI stays off. Buttons, reminders and briefings keep working; I will not process free text. Enable it any time by simply writing to me again.",
  voice_consent_prompt:
    "For AI processing, text is sent to the external provider, and voice goes to OpenAI only for transcription. Audio is not stored; the recognised text is processed and kept like an ordinary message. Allow?",
  voice_consent_granted: "Voice input is on. Send the voice message again: audio is not resent automatically.",
  voice_consent_declined_toast: "Voice input not enabled",

  chat_nothing_to_retry: "There are no saved messages waiting for AI processing.",
  chat_ai_suspended: "AI processing is suspended for this account. Reminders and buttons keep working.",
  chat_ai_unavailable: "AI is unavailable right now. Your message is saved: send /retry_ai whenever you want to retry. Reminders and buttons keep working.",
  chat_rate_limited: "The hourly AI limit is reached ({limit} messages). I can read text again after {until}. Buttons, reminders and briefings work as usual.",
  text_failed: "Could not process the message. Nothing changed; I will try again myself.",
  ai_retry_exhausted: "I still could not process the message: \u201c{preview}\u201d. Nothing changed. Try again: /retry_ai",
  text_uncertain: "I am not sure whether the change was saved. Do not repeat it yet: I will check and tell you.",
  end_done: "Conversation ended. Everything already saved stays.",
  end_none: "There is no active review right now.",
  until_morning: "All right. Quiet until {until}.",

  timezone_usage: "Send a city or a timezone. For example: “Berlin” or “Europe/Berlin”.",
  timezone_set: "Main timezone: {timezone}. Existing tasks are not shifted. Briefings and quiet hours still use the previous zone: apply the new one to them too?",
  timezone_invalid: "I do not know that timezone. Send a city, for example “Berlin”, or a zone like Europe/Berlin.",
  time_invalid: "Invalid time. Use HH:MM, for example 09:30.",

  onb_timezone_prompt: "What is your timezone? Briefing times and phrases like “tomorrow at 10” depend on it. Send a city, for example “Berlin”, or pick one below.",
  profile_title: "🧭 Your context",
  profile_empty: "Nothing here yet.",
  profile_opening_question:
    "Answer freely, skip anything, or stop whenever you like. Let us start simple: what does your day usually look like — when do you get up, when do you go to bed, and which hours are bad for anything important?",
  chat_too_many_questions: "That is five questions in a row from me. Say to stop asking and I will conclude from what I have.",
  onb_step_unclear: "Answer yes or no, or tap a button.",
  onb_timezone_other: "Other",
  onb_timezone_saved_toast: "Timezone saved",

  bad_command_toast: "Invalid command",
  done_toast: "Done",
  back_button: "← Back",
  not_now_button: "✖️ Not now",

  webapp_open_button: "📲 Open in the app",
  webapp_open_task_button: "📲 Open the task",
  webapp_profile_hint: "Your profile, and everything I remember about you, is in the app.",

  scope_overdue: "overdue",
  week_plan_summary: "Closed last week: {done}. Taken and not started: {stale}.",
  group_next: "next",
  label_main: "Main",
  nothing_planned: "Nothing is planned.",
  list_more: "+ {count} more",
  briefing_morning_title: "☀️ Today",
  briefing_weekly_title: "🗂 Week plan",
  briefing_goals_idle: "Goals with no movement:",
  briefing_goal_idle_days: "quiet for {days} days",
  goal_step_button: "💡 Next step: {title}",
  goal_step_prompt: "What should I do about the goal «{title}»? Suggest one concrete step for this week.",
  goal_step_gone_toast: "That goal is no longer active",
  briefing_taken_week: "Taken this week:",
  briefing_week_cta: "Pick next week's tasks in the app.",
  briefing_pool_empty: "The pool has no undated tasks.",

  confirm_button: "Confirm",
  decline_button: "No, thanks",
  undo_button: "↩️ Put it back",
  undo_reschedule_button: "↩️ Undo the move",
  confirm_toast: "Confirmed ✓",
  confirm_toast_many: "Confirmed: {count}",
  confirmed_text: "Confirmed.",
  declined_toast: "Dropped",
  already_handled_toast: "Already handled",
  undo_toast: "Put back as it was",
  undo_text: "↩️ Put back as it was. The change is undone:",
  action_stale_toast: "Can no longer be undone: more than a day passed or the task changed since",
  action_uncertain_toast: "Not sure it was saved. I will check and tell you",
  action_done_undo_hint: "Can be undone within a day.",

  task_not_found_toast: "Task not found",
  task_unavailable_toast: "The task is no longer available",
  state_changed_toast: "The state already changed or the action is unavailable",
  resched_prompt_toast: "When to come back?",
  done_occurrence_toast: "Done ✓",
  skipped_toast: "Skipped",
  cancelled_occurrence_toast: "Cancelled",

  reason_toast: "Why are you moving it?",
  reason_prompt_text: "🕒 {title}\n\nWhy are you moving it? Write briefly in one message.",
  reason_write_toast: "Write the reason",
  rescheduled_toast: "Moved",
  rescheduled_text: "Moved.",
  rescheduled_fuzzy_text: "Returned the task to loose planning.",
  resched_failed_toast: "Could not move it",
  resched_failed_text: "Could not move it. Say the new time again, for example “tomorrow at 10” or “Fri 15:00–16:00”.",
  reason_too_short: "Could not move it. Write briefly why you are moving it, once more.",
  repeated_reschedule: "This is a repeated move. If the problem is not only the time, you can record what is stopping you from starting.",

  followup_failed_toast: "Could not change the check",
  snooze_reminder_toast: "I will remind you later",
  snooze_15m_button: "⏰ In 15 min",
  snooze_1h_button: "⏰ In an hour",

  quiet_deferred_notice: "🔕 Was in quiet hours, showing it now",
  escalation_header: "🔴 Past the deadline — reminder #{n}",
  mute_escalation_button: "🔕 Enough for this task",
  mute_escalation_toast: "No more reminders for this task",

  voice_suspended: "AI processing is suspended for this account. Voice input is unavailable.",
  ai_spend_warning: "Heads-up: estimated AI spend this month reached ${amount}. This is only a notice; AI is not switched off automatically.",
  ai_spend_owner_notice: "IPsycho: user {userId} reached the AI spend warning of ${amount}.",
  ops_alert: "IPsycho: the reminder queue needs attention. {details}",
  voice_too_long: "The voice message is too long or too large. Send a recording up to {minutes} min and {mb} MB, or text.",
  voice_openai_only: "Voice input is available only with OpenAI configured.",
  voice_rate_limited: "The hourly AI limit is reached. Try later; buttons and reminders keep working.",
  voice_recognizing: "🎙 Transcribing…",
  voice_consent_needed: "AI processing needs your consent.",
  voice_unavailable: "Voice input is unavailable right now.",
  voice_unrecognized: "Could not recognise the speech. Try a shorter recording or send text.",
  voice_failed: "Could not process the voice message. Try sending a shorter one or write text.",

  // The browsing screens moved to the Mini App (task 11). Their commands and their buttons still
  // answer for one release, with this sentence and a launch button — an unanswered callback leaves a
  // spinner, and the sentence has to stand on its own when WEBAPP_ENABLED is off and there is no button.
  moved_to_app: "Lists, filters and settings live in the IPsycho app now. The conversation stays here: say what to create, change, move, or close.",
  moved_to_app_toast: "This is in the app now",
};
