/** Russian is the reference dictionary: every key here must exist in uk.ts and en.ts. */
export const ru = {
  // Access and registration
  access_denied: "Этот бот закрытый. Попроси у владельца персональную ссылку-приглашение.",
  access_denied_toast: "Нет доступа",
  private_only: "Я работаю только в личных сообщениях: там у каждого свой отдельный список задач.",
  invite_invalid: "Эта ссылка-приглашение недействительна, просрочена или уже использована.",
  invite_already_registered: "У тебя уже есть аккаунт в этом боте, ссылка не нужна. Если бот не отвечает, напиши владельцу.",
  invite_created:
    "Отправь эту персональную ссылку новому пользователю:\n{link}\n\nОна действует один раз в течение {days} дней. У человека будет отдельное пространство без доступа к твоим данным.",
  invite_not_allowed: "Создавать ссылки-приглашения может только владелец проекта.",
  invite_failed: "Не удалось создать ссылку-приглашение. Попробуй позже.",
  settings_missing: "Настройки аккаунта не найдены. Напиши /start, чтобы создать их заново.",
  unsupported_message: "Пока понимаю только текст и голосовые. Опиши словами, что нужно сделать. Например: «встреча в четверг в 16:00».",

  // Status
  status_server: "✅ Сервер IPsycho доступен",
  status_db_ok: "✅ PostgreSQL отвечает",
  status_db_failed: "❌ PostgreSQL не отвечает",
  status_telegram: "✅ Telegram доставил этот ответ",
  status_ai_configured: "🤖 AI: настроен ({provider})",
  status_ai_missing: "🤖 AI: не настроен",
  status_ai_suspended: "🤖 AI: приостановлен для аккаунта",
  status_deliveries: "🔔 Напоминаний в очереди: {pending}",
  status_deliveries_ambiguous: "⚠️ Доставок с неизвестным исходом: {ambiguous}",

  // History, cancel
  history_cleared: "AI-история очищена ({count} сообщений). Сообщения Telegram, задачи, цели, напоминания и настройки не изменены.",
  history_cleared_toast: "AI-история очищена ({count})",
  cancel_done: "Текущий ввод и разбор остановлены. Уже сохранённые задачи и решения не изменены.",

  // Account
  delete_prompt:
    "Удаление остановит AI, сводки и напоминания сразу. Данные будут окончательно удалены через {days} дней; до этого аккаунт можно восстановить командой /restore. Остаточные данные могут сохраняться в зашифрованных резервных копиях: {daily} ежедневных и {weekly} еженедельных.",
  delete_confirm_button: "Подтвердить удаление",
  delete_scheduled_toast: "Удаление запланировано",
  delete_scheduled: "Аккаунт заблокирован. В течение {days} дней его можно восстановить командой /restore.",
  delete_failed_toast: "Не удалось запланировать удаление",
  delete_unavailable_toast: "Аккаунт уже недоступен",
  restore_done: "Аккаунт восстановлен. Будущие напоминания снова активны.",
  restore_unavailable: "Аккаунт не ожидает удаления или срок восстановления уже истёк.",
  ai_revoked: "Согласие на внешнюю AI-обработку отозвано. Напоминания, сводки и кнопки продолжат работать.",
  retry_failed: "Повторная обработка пока не удалась. Сообщение сохранено.",

  // Consent
  consent_prompt:
    "Для AI-чата текст сообщений будет отправляться внешнему провайдеру {provider}. Голосовые при OpenAI отправляются только для расшифровки и не сохраняются как аудио. Разрешить такую обработку?",
  consent_yes_button: "Согласен",
  consent_no_button: "Не сейчас",
  consent_granted_toast: "Согласие сохранено",
  consent_granted_replaying: "Готово, обрабатываю твоё последнее сообщение.",
  consent_granted: "Готово. Напиши, что нужно сделать.",
  consent_declined_toast: "AI не включён",
  consent_declined:
    "Хорошо, AI выключен. Кнопки, напоминания и сводки продолжат работать; свободный текст я разбирать не буду. Включить можно в любой момент: просто напиши мне ещё раз.",
  voice_consent_prompt:
    "Для AI-обработки текст будет отправляться внешнему провайдеру, а голосовое — OpenAI только для расшифровки. Аудио не сохраняется; распознанный текст обрабатывается и хранится как обычное сообщение. Разрешить?",
  voice_consent_granted: "Голосовой ввод включён. Отправь голосовое ещё раз: аудио не переотправляется автоматически.",
  voice_consent_declined_toast: "Голосовой ввод не включён",

  // Chat gates
  chat_nothing_to_retry: "Нет сохранённых сообщений, которые ждут AI-обработки.",
  chat_ai_suspended: "AI-обработка для аккаунта приостановлена. Напоминания и кнопки продолжают работать.",
  chat_ai_unavailable: "AI сейчас недоступен. Сообщение сохранено: напиши /retry_ai, когда захочешь повторить. Напоминания и кнопки работают.",
  chat_rate_limited: "Достигнут часовой лимит AI ({limit} сообщений). Снова смогу разбирать текст после {until}. Кнопки, напоминания и сводки работают как обычно.",
  text_failed: "Не удалось обработать сообщение. Ничего не изменилось; можно повторить запрос позже.",
  text_uncertain: "Не уверен, сохранилось ли изменение. Не повторяй пока: я проверю сам и напишу. Открыть список: /today",
  end_done: "Разговор закончен. Всё, что уже сохранено, остаётся.",
  end_none: "Сейчас нет активного разбора.",
  until_morning: "Хорошо. Молчу до {until}.",

  // Settings commands
  timezone_usage: "Напиши город или часовой пояс. Например: /timezone Берлин или /timezone Europe/Berlin",
  timezone_set: "Основной часовой пояс: {timezone}. Уже созданные задачи не сдвигаются. Сводки и тихие часы пока остаются в прежнем поясе: применить новый и к ним?",
  timezone_invalid: "Не знаю такой часовой пояс. Напиши город, например «Берлин», или пояс вида Europe/Berlin.",
  tz_apply_digests: "К сводкам",
  tz_apply_quiet: "К тихим часам",
  tz_apply_both: "К обоим",
  tz_keep: "Оставить как есть",
  tz_applied_toast: "Часовой пояс применён",
  language_auto: "Язык интерфейса снова определяется по Telegram.",
  language_set: "Язык интерфейса закреплён: {language}. AI всё равно отвечает на языке текущего сообщения.",
  language_usage: "Формат: /language auto, /language ru, /language uk или /language en",
  digest_usage: "Сводка сейчас: /{kind}\nВключить: /{kind} on HH:MM\nВыключить: /{kind} off",
  digest_on_morning: "Утренняя сводка включена.",
  digest_on_evening: "Вечерняя сводка включена.",
  digest_off: "Сводка выключена.",
  time_invalid: "Неверное время. Используй формат HH:MM, например 09:30.",
  weekly_usage: "Обзор сейчас: /weekly\nНачать планирование: /weekly review\nВключить: /weekly on <день 1-7> <HH:MM>\nВыключить: /weekly off",
  weekly_on: "Недельный обзор включён.",
  weekly_off: "Недельный обзор выключен.",
  weekly_invalid: "Не удалось изменить настройку. Проверь день недели (1–7) и время HH:MM.",
  quiet_default: "Тихие часы: будни 22:00–08:00, выходные 23:00–09:00.",
  quiet_off: "Тихие часы выключены.",
  quiet_updated: "Тихие часы обновлены.",
  quiet_usage: "Формат: /quiet default, /quiet off или /quiet 22:00 08:00 23:00 09:00",
  snooze_off: "Временная тишина выключена.",
  snooze_until: "Молчу до {until}.",
  snooze_usage: "Формат: /snooze morning, /snooze off или /snooze <минуты 15..10080>",
  snooze_failed: "Не удалось изменить временную тишину.",
  rd_seen: "Интервалы «Увидел» обновлены.",
  rd_event: "Стандартные напоминания событий обновлены.{warning}",
  rd_event_warning: " Напоминаний много или часть стоит ближе 15 минут: слишком близкие будут объединены.",
  rd_task: "Стандартное напоминание плановой задачи обновлено.",
  rd_critical: "Интервал критической эскалации обновлён.",
  rd_usage: "Примеры: /reminder_defaults seen 60 30 15; event -60,-15,0; task 0; critical 60",
  rd_failed: "Не удалось изменить настройку. Проверь числа и формат команды.",

  // Onboarding
  onb_timezone_prompt: "В каком ты часовом поясе? От этого зависит время сводок и разбор фраз вроде «завтра в 10». Напиши город, например «Берлин», или выбери ниже.",
  onb_timezone_other: "Другой",
  onb_timezone_saved_toast: "Часовой пояс сохранён",

  // Generic toasts and buttons
  bad_command_toast: "Некорректная команда",
  saved_toast: "Сохранено",
  done_toast: "Готово",
  back_button: "← Назад",
  not_now_button: "✖️ Не сейчас",
  today_button: "☀️ Сегодня",
  tasks_button: "📋 Все задачи",
  to_tasks_button: "← К задачам",
  settings_button: "⚙️ Настройки",
  reminders_button: "🔔 Напоминания",
  goals_button: "🎯 Цели",
  collapse_button: "Свернуть",
  show_all_button: "Показать все ({count})",
  help_button: "📖 Как это работает",
  guide_back_button: "← Помощь",

  // Prefs / settings screen
  prefs_snooze_toast: "Молчу до утра",
  prefs_failed_toast: "Не удалось изменить настройку",
  prefs_morning_on: "☀️ Утро: вкл",
  prefs_morning_off: "☀️ Утро: выкл",
  prefs_evening_on: "🌙 Вечер: вкл",
  prefs_evening_off: "🌙 Вечер: выкл",
  prefs_weekly_on: "📅 Обзор: вкл",
  prefs_weekly_off: "📅 Обзор: выкл",
  prefs_quiet_on: "🔕 Тихие часы: вкл",
  prefs_quiet_off: "🔕 Тихие часы: выкл",
  prefs_snooze_morning: "🔕 До утра",
  prefs_weekly_start: "🗓 Спланировать неделю",
  prefs_context: "🧭 Контекст",
  prefs_clear_history: "🧠 Очистить AI-историю",

  // Reminders screen
  reminders_title: "🔔 Ближайшие напоминания",
  reminders_none: "🔔 Напоминания\n\nБлижайших напоминаний нет.",
  reminders_hint: "Нажми на напоминание, чтобы отменить его. Перенести можно обычным сообщением.",
  reminder_cancel_button: "✖ {title} · {when}",
  reminder_cancelled_toast: "Напоминание отменено",
  reminder_already_toast: "Оно уже отправлено или отменено",
  reminder_cancel_failed_toast: "Не удалось отменить напоминание",

  // Action cards
  confirm_button: "Подтвердить",
  decline_button: "Не надо",
  undo_button: "↩️ Вернуть как было",
  undo_reschedule_button: "↩️ Отменить перенос",
  confirm_toast: "Подтверждено ✓",
  confirm_toast_many: "Подтверждено: {count}",
  confirmed_text: "Подтверждено.",
  declined_toast: "Отменено",
  already_handled_toast: "Уже обработано",
  undo_toast: "Вернул как было",
  undo_text: "↩️ Вернул как было. Изменение отменено:",
  action_stale_toast: "Уже нельзя отменить: прошло больше суток или задача успела измениться",
  action_uncertain_toast: "Не уверен, что записалось. Проверю сам и напишу",
  action_done_undo_hint: "Отменить можно в течение суток.",

  // Occurrence buttons
  task_not_found_toast: "Задача не найдена",
  task_unavailable_toast: "Задача уже недоступна",
  state_changed_toast: "Состояние уже изменилось или действие недоступно",
  not_in_progress_toast: "Задача уже не в работе",
  check_prompt_toast: "Когда проверить результат?",
  resched_prompt_toast: "Когда вернуться?",
  seen_toast: "Вернусь к задаче позже",
  blocker_prompt_toast: "Расскажи, что мешает",
  blocker_prompt_text: "🧱 {title}\n\nЧто мешает начать? Напиши одним сообщением или нажми кнопку.",
  cancel_what_toast: "Что отменить?",
  cancel_one_button: "Только это",
  cancel_series_button: "Всю серию",
  started_toast: "Начато",
  done_occurrence_toast: "Готово ✓",
  skipped_toast: "Пропущено",
  cancelled_occurrence_toast: "Отменено",
  reschedule_button: "🕒 Перенести",
  cancel_task_button: "❌ Отменить",

  // Quick reschedule
  resched_custom_toast: "Напиши новое время",
  resched_prompt: "Напиши, когда: {hint}. Можно добавить причину в этом же сообщении.",
  resched_hint_window: "например «завтра 10:00–11:00»",
  resched_hint_deadline: "например «до пятницы» или «до 12.09 18:00»",
  resched_hint_point: "например «завтра в 10» или «пн 9:30»",
  reason_toast: "Почему переносишь?",
  reason_prompt_text: "🕒 {title}\n\nПочему переносишь? Напиши коротко одним сообщением.",
  reason_write_toast: "Напиши причину",
  rescheduled_toast: "Перенесено",
  rescheduled_text: "Перенесено.",
  rescheduled_fuzzy_text: "Вернул задачу в нечёткое планирование.",
  resched_failed_toast: "Не удалось перенести",
  resched_failed_text: "Не удалось перенести. Скажи новое время ещё раз, например «завтра в 10» или «пт 15:00–16:00».",
  reason_too_short: "Не удалось перенести. Напиши коротко, почему переносишь, ещё раз.",
  repeated_reschedule: "Это уже повторный перенос. Если проблема не только во времени, можно зафиксировать, что именно мешает начать.",
  cant_start_button: "Не могу начать",
  started_button: "Начал",
  blocker_failed: "Не удалось продолжить AI-разбор сейчас. Описание препятствия сохранено; если сообщение ждёт AI, его можно повторить через /retry_ai.",

  // Follow-ups / snooze
  followup_none_toast: "Проверки не будет",
  followup_custom_toast: "Напиши время",
  followup_custom_prompt: "Напиши: количество минут (минимум 15), HH:MM или YYYY-MM-DD HH:MM.",
  followup_updated_toast: "Обновлено",
  followup_failed_toast: "Не удалось изменить проверку",
  followup_done: "Готово. Напомню {when}.",
  followup_parse_failed: "Не понял время. Напиши минуты, HH:MM или YYYY-MM-DD HH:MM.",
  snooze_reminder_toast: "Напомню позже",
  snooze_15m_button: "⏰ Через 15 мин",
  snooze_1h_button: "⏰ Через час",
  snooze_evening_button: "⏰ Вечером",

  // Series
  series_paused: "Серия на паузе",
  series_cancelled: "Серия отменена",
  series_not_found_toast: "Серия не найдена",
  series_changed_toast: "Серия уже изменилась",

  // Topics / reviews
  topic_ended_toast: "Закончено",
  topic_already_ended_toast: "Уже завершено",
  topic_concluding_toast: "Делаю вывод",
  review_stale_toast: "Эта кнопка обзора уже устарела",
  review_start_evening_toast: "Начинаю разбор",
  review_start_weekly_toast: "Начинаю планирование",
  review_failed: "Не удалось запустить обзор. Попробуй позже.",
  review_header_evening: "💭 Вечерний разбор",
  review_header_weekly: "🗓 Планирование недели",
  review_header_done: "готово",
  review_end_evening_button: "Закончить разбор",
  review_end_weekly_button: "Закончить планирование",

  // Reminder notices
  quiet_deferred_notice: "🔕 Было в тихие часы, показываю сейчас",
  escalation_header: "🔴 Срок прошёл — {n}-е напоминание",
  mute_escalation_button: "🔕 Хватит по этой задаче",
  mute_escalation_toast: "Больше не напоминаю по этой задаче",

  // Voice
  voice_suspended: "AI-обработка для аккаунта приостановлена. Голосовой ввод недоступен.",
  ai_spend_warning: "Предупреждение: оценочные расходы AI в этом месяце достигли ${amount}. Это только уведомление; AI автоматически не отключается.",
  ai_spend_owner_notice: "IPsycho: пользователь {userId} достиг AI spend warning ${amount}.",
  voice_too_long: "Голосовое слишком длинное или большое. Отправь запись до {minutes} мин и {mb} МБ либо текст.",
  voice_openai_only: "Голосовой ввод сейчас доступен только при настроенном OpenAI.",
  voice_rate_limited: "Достигнут часовой лимит AI. Попробуй позже, кнопки и напоминания работают.",
  voice_recognizing: "🎙 Распознаю…",
  voice_consent_needed: "Нужно подтвердить AI-обработку.",
  voice_unavailable: "Голосовой ввод сейчас недоступен.",
  voice_unrecognized: "Не удалось распознать речь. Попробуй записать короче или отправь текст.",
  voice_failed: "Не удалось обработать голосовое. Попробуй отправить его короче или напиши текст.",
} as const;
