import type { ru } from "./ru.js";

export const uk: Record<keyof typeof ru, string> = {
  access_denied: "Цей бот приватний. Попроси у власника персональне посилання-запрошення.",
  access_denied_toast: "Немає доступу",
  private_only: "Я працюю лише в особистих повідомленнях: там у кожного свій окремий список завдань.",
  invite_invalid: "Це посилання-запрошення недійсне, прострочене або вже використане.",
  invite_already_registered: "У тебе вже є акаунт у цьому боті, посилання не потрібне. Якщо бот не відповідає, напиши власнику.",
  invite_created:
    "Надішли це персональне посилання новому користувачу:\n{link}\n\nВоно діє один раз протягом {days} днів. У людини буде окремий простір без доступу до твоїх даних.",
  invite_not_allowed: "Створювати посилання-запрошення може лише власник проєкту.",
  invite_failed: "Не вдалося створити посилання-запрошення. Спробуй пізніше.",
  settings_missing: "Налаштування акаунта не знайдено. Напиши /start, щоб створити їх заново.",
  unsupported_message: "Поки розумію лише текст і голосові. Опиши словами, що потрібно зробити. Наприклад: «зустріч у четвер о 16:00».",

  status_server: "✅ Сервер IPsycho доступний",
  status_db_ok: "✅ PostgreSQL відповідає",
  status_db_failed: "❌ PostgreSQL не відповідає",
  status_telegram: "✅ Telegram доставив цю відповідь",
  status_ai_configured: "🤖 AI: налаштований ({provider})",
  status_ai_missing: "🤖 AI: не налаштований",
  status_ai_suspended: "🤖 AI: призупинений для акаунта",
  status_deliveries: "🔔 Нагадувань у черзі: {pending}",
  status_deliveries_ambiguous: "⚠️ Доставок із невідомим результатом: {ambiguous}",

  history_cleared: "AI-історію очищено ({count} повідомлень). Повідомлення Telegram, завдання, цілі, нагадування й налаштування не змінені.",
  history_cleared_toast: "AI-історію очищено ({count})",
  cancel_done: "Поточне введення й розбір зупинено. Уже збережені завдання й рішення не змінені.",

  delete_prompt:
    "Видалення одразу зупинить AI, зведення та нагадування. Дані буде остаточно видалено через {days} днів; до цього акаунт можна відновити командою /restore. Залишкові дані можуть зберігатися в зашифрованих резервних копіях: {daily} щоденних і {weekly} щотижневих.",
  delete_confirm_button: "Підтвердити видалення",
  delete_scheduled_toast: "Видалення заплановано",
  delete_scheduled: "Акаунт заблоковано. Протягом {days} днів його можна відновити командою /restore.",
  delete_failed_toast: "Не вдалося запланувати видалення",
  delete_unavailable_toast: "Акаунт уже недоступний",
  restore_done: "Акаунт відновлено. Майбутні нагадування знову активні.",
  restore_unavailable: "Акаунт не очікує видалення або термін відновлення вже минув.",
  ai_revoked: "Згоду на зовнішню AI-обробку відкликано. Нагадування, зведення й кнопки працюватимуть далі.",
  retry_failed: "Повторна обробка поки не вдалася. Повідомлення збережено.",

  consent_prompt:
    "Для AI-чату текст повідомлень надсилатиметься зовнішньому провайдеру {provider}. Голосові при OpenAI надсилаються лише для розшифровки й не зберігаються як аудіо. Дозволити таку обробку?",
  consent_yes_button: "Погоджуюсь",
  consent_no_button: "Не зараз",
  consent_granted_toast: "Згоду збережено",
  consent_granted_replaying: "Готово, обробляю твоє останнє повідомлення.",
  consent_granted: "Готово. Напиши, що потрібно зробити.",
  consent_declined_toast: "AI не ввімкнено",
  consent_declined:
    "Гаразд, AI вимкнено. Кнопки, нагадування й зведення працюватимуть далі; вільний текст я розбирати не буду. Увімкнути можна будь-коли: просто напиши мені ще раз.",
  voice_consent_prompt:
    "Для AI-обробки текст надсилатиметься зовнішньому провайдеру, а голосове — OpenAI лише для розшифровки. Аудіо не зберігається; розпізнаний текст обробляється й зберігається як звичайне повідомлення. Дозволити?",
  voice_consent_granted: "Голосове введення ввімкнено. Надішли голосове ще раз: аудіо не переноситься автоматично.",
  voice_consent_declined_toast: "Голосове введення не ввімкнено",

  chat_nothing_to_retry: "Немає збережених повідомлень, що чекають на AI-обробку.",
  chat_ai_suspended: "AI-обробку для акаунта призупинено. Нагадування й кнопки працюють.",
  chat_ai_unavailable: "AI зараз недоступний. Повідомлення збережено: напиши /retry_ai, коли захочеш повторити. Нагадування й кнопки працюють.",
  chat_rate_limited: "Досягнуто годинний ліміт AI ({limit} повідомлень). Знову зможу розбирати текст після {until}. Кнопки, нагадування й зведення працюють як звичайно.",
  text_failed: "Не вдалося обробити повідомлення. Нічого не змінилося; я спробую ще раз сам.",
  ai_retry_exhausted: "Так і не зміг обробити повідомлення: «{preview}». Нічого не змінилося. Спробувати ще раз: /retry_ai",
  text_uncertain: "Не впевнений, чи збереглася зміна. Поки не повторюй: я перевірю сам і напишу. Відкрити список: /today",
  end_done: "Розмову закінчено. Усе, що вже збережено, залишається.",
  end_none: "Зараз немає активного розбору.",
  until_morning: "Гаразд. Мовчу до {until}.",

  timezone_usage: "Напиши місто або часовий пояс. Наприклад: /timezone Берлін або /timezone Europe/Berlin",
  timezone_set: "Основний часовий пояс: {timezone}. Уже створені завдання не зсуваються. Зведення й тихі години поки залишаються в попередньому поясі: застосувати новий і до них?",
  timezone_invalid: "Не знаю такого часового поясу. Напиши місто, наприклад «Берлін», або пояс на кшталт Europe/Berlin.",
  tz_apply_digests: "До зведень",
  tz_apply_quiet: "До тихих годин",
  tz_apply_both: "До обох",
  tz_keep: "Залишити як є",
  tz_applied_toast: "Часовий пояс застосовано",
  language_auto: "Мова інтерфейсу знову визначається за Telegram.",
  language_set: "Мову інтерфейсу закріплено: {language}. AI усе одно відповідає мовою поточного повідомлення.",
  language_usage: "Формат: /language auto, /language ru, /language uk або /language en",
  digest_usage: "Зведення зараз: /{kind}\nУвімкнути: /{kind} on HH:MM\nВимкнути: /{kind} off",
  digest_on_morning: "Ранкове зведення ввімкнено.",
  digest_off: "Зведення вимкнено.",
  time_invalid: "Невірний час. Використовуй формат HH:MM, наприклад 09:30.",
  weekly_usage: "Картка тижня зараз: /weekly\nПлан тижня: /week\nУвімкнути: /weekly on <день 1-7> <HH:MM>\nВимкнути: /weekly off",
  weekly_on: "Картку тижня увімкнено.",
  weekly_off: "Картку тижня вимкнено.",
  weekly_invalid: "Не вдалося змінити налаштування. Перевір день тижня (1–7) і час HH:MM.",
  quiet_default: "Тихі години: будні 22:00–08:00, вихідні 23:00–09:00.",
  quiet_off: "Тихі години вимкнено.",
  quiet_updated: "Тихі години оновлено.",
  quiet_usage: "Формат: /quiet default, /quiet off або /quiet 22:00 08:00 23:00 09:00",
  snooze_off: "Тимчасову тишу вимкнено.",
  snooze_until: "Мовчу до {until}.",
  snooze_usage: "Формат: /snooze morning, /snooze off або /snooze <хвилини 15..10080>",
  snooze_failed: "Не вдалося змінити тимчасову тишу.",
  rd_event: "Стандартні нагадування подій оновлено.{warning}",
  rd_event_warning: " Нагадувань багато або частина стоїть ближче ніж 15 хвилин: надто близькі буде об'єднано.",
  rd_task: "Стандартне нагадування планового завдання оновлено.",
  rd_critical: "Інтервал критичної ескалації оновлено.",
  rd_usage: "Приклади: /reminder_defaults seen 60 30 15; event -60,-15,0; task 0; critical 60",
  rd_failed: "Не вдалося змінити налаштування. Перевір числа й формат команди.",

  onb_timezone_prompt: "У якому ти часовому поясі? Від цього залежить час зведень і розбір фраз на кшталт «завтра о 10». Напиши місто, наприклад «Берлін», або вибери нижче.",
  onb_timezone_other: "Інший",
  onb_timezone_saved_toast: "Часовий пояс збережено",

  bad_command_toast: "Некоректна команда",
  saved_toast: "Збережено",
  done_toast: "Готово",
  back_button: "← Назад",
  not_now_button: "✖️ Не зараз",
  today_button: "☀️ Сьогодні",
  tasks_button: "📋 Усі завдання",
  to_tasks_button: "← До завдань",
  settings_button: "⚙️ Налаштування",
  reminders_button: "🔔 Нагадування",
  goals_button: "🎯 Цілі",
  help_button: "📖 Як це працює",

  tasks_header: "📋 Завдання · {scope} ({count})",
  tasks_scope_empty: "У цьому фільтрі порожньо.",
  tasks_hint: "Щоб змінити, завершити або перенести завдання, напиши це звичайним повідомленням.",
  scope_overdue: "прострочено",
  scope_today: "сьогодні",
  scope_week: "тиждень",
  scope_month: "місяць",
  scope_all: "усі",
  scope_nodate: "без дати",
  scope_overdue_button: "⚠️ {count}",
  scope_today_button: "Сьогодні",
  scope_week_button: "Тиждень",
  scope_month_button: "Місяць",
  scope_all_button: "Усі",
  scope_nodate_button: "🫧 Без дати",
  paused_series_button: "⏸ На паузі: {count}",
  week_plan_header: "🗂 План тижня з {monday}",
  week_plan_summary: "За минулий тиждень закрито: {done}. Взято й не почато: {stale}.",
  week_plan_hint: "Тапни завдання, щоб узяти його на тиждень або повернути в пул.",
  week_plan_empty: "У пулі немає завдань без дати. Опиши справу словами — і вона з\u2019явиться тут.",
  week_plan_button: "🗂 Тиждень",
  week_picked_toast: "Узяв на цей тиждень",
  week_released_toast: "Повернув у пул",
  week_full_toast: "На тиждень уже взято {limit} завдань. Поверни одне, щоб додати інше.",
  week_pick_gone_toast: "Це завдання вже не в пулі",
  week_taken_section: "Взято на тиждень:",
  week_take_today_toast: "Поставив на сьогодні",
  week_take_today_row: "▶️ Сьогодні: {title}",
  week_take_today_failed_toast: "Не зміг поставити на сьогодні",
  resume_series_button: "▶️ {title}",
  paused_series_header: "⏸ Серії на паузі: {count}",
  paused_series_empty: "Жодна серія не стоїть на паузі.",
  series_resumed: "Серія знову йде",
  group_next: "найбл.",
  group_open_hint: "Рядки зі стрілкою ▸ розкриваються: там кілька дат.",
  page_next_button: "Ще {count} →",
  page_prev_button: "← Попередні",
  today_stale: "⚠️ Прострочено раніше: {count}",
  today_stale_button: "⚠️ Прострочене ({count})",
  list_changed_toast: "Список змінився, оновив",
  guide_back_button: "← Допомога",

  prefs_snooze_toast: "Мовчу до ранку",
  prefs_failed_toast: "Не вдалося змінити налаштування",
  prefs_morning_on: "☀️ Ранок: увімк",
  prefs_morning_off: "☀️ Ранок: вимк",
  prefs_weekly_on: "📅 Тиждень: увімк",
  prefs_weekly_off: "📅 Тиждень: вимк",
  prefs_quiet_on: "🔕 Тихі години: увімк",
  prefs_quiet_off: "🔕 Тихі години: вимк",
  prefs_snooze_morning: "🔕 До ранку",
  prefs_context: "🧭 Контекст",
  prefs_clear_history: "🧠 Очистити AI-історію",

  reminders_title: "🔔 Найближчі нагадування",
  reminders_none: "🔔 Нагадування\n\nНайближчих нагадувань немає.",
  reminders_hint: "Натисни на нагадування, щоб скасувати його. Перенести можна звичайним повідомленням.",
  reminders_day_today: "Сьогодні",
  reminders_day_tomorrow: "Завтра",
  goals_header: "🎯 Цілі · {scope} ({count})",
  goals_scope_active: "активні",
  goals_scope_paused: "на паузі",
  goals_scope_completed: "завершені",
  goals_scope_active_button: "Активні",
  goals_scope_paused_button: "На паузі",
  goals_scope_completed_button: "Завершені",
  goals_empty_scope: "У цьому фільтрі цілей немає.",
  goals_no_tasks: "пов'язаних активних завдань немає",
  goals_hint: "Щоб змінити ціль або пов'язати завдання, напиши це звичайним повідомленням.",
  goal_why: "Навіщо",
  goal_deadline: "до {date}",
  settings_section_time: "Час і мова",
  settings_section_digests: "Зведення",
  settings_section_quiet: "Тиша і дані",
  settings_timezone_button: "🌍 Часовий пояс",
  settings_language_button: "🗣 Мова",
  settings_language_prompt: "Яку мову інтерфейсу використовувати?",
  settings_language_auto_button: "Як у Telegram",
  reminder_cancel_button: "✖ {title} · {when}",
  reminder_cancelled_toast: "Нагадування скасовано",
  reminder_already_toast: "Його вже надіслано або скасовано",
  reminder_cancel_failed_toast: "Не вдалося скасувати нагадування",

  confirm_button: "Підтвердити",
  decline_button: "Не треба",
  undo_button: "↩️ Повернути як було",
  undo_reschedule_button: "↩️ Скасувати перенесення",
  confirm_toast: "Підтверджено ✓",
  confirm_toast_many: "Підтверджено: {count}",
  confirmed_text: "Підтверджено.",
  declined_toast: "Скасовано",
  already_handled_toast: "Уже оброблено",
  undo_toast: "Повернув як було",
  undo_text: "↩️ Повернув як було. Зміну скасовано:",
  action_stale_toast: "Уже не можна скасувати: минуло більше доби або завдання встигло змінитися",
  action_uncertain_toast: "Не впевнений, що записалося. Перевірю сам і напишу",
  action_done_undo_hint: "Скасувати можна протягом доби.",

  task_not_found_toast: "Завдання не знайдено",
  task_unavailable_toast: "Завдання вже недоступне",
  state_changed_toast: "Стан уже змінився або дія недоступна",
  resched_prompt_toast: "Коли повернутися?",
  cancel_what_toast: "Що скасувати?",
  cancel_one_button: "Лише це",
  cancel_series_button: "Усю серію",
  done_occurrence_toast: "Готово ✓",
  skipped_toast: "Пропущено",
  cancelled_occurrence_toast: "Скасовано",
  reschedule_button: "🕒 Перенести",
  cancel_task_button: "❌ Скасувати",

  resched_custom_toast: "Напиши новий час",
  resched_prompt: "Напиши, коли: {hint}. Можна додати причину в цьому ж повідомленні.",
  resched_hint_window: "наприклад «завтра 10:00–11:00»",
  resched_hint_deadline: "наприклад «до п'ятниці» або «до 12.09 18:00»",
  resched_hint_point: "наприклад «завтра о 10» або «пн 9:30»",
  reason_toast: "Чому переносиш?",
  reason_prompt_text: "🕒 {title}\n\nЧому переносиш? Напиши коротко одним повідомленням.",
  reason_write_toast: "Напиши причину",
  rescheduled_toast: "Перенесено",
  rescheduled_text: "Перенесено.",
  rescheduled_fuzzy_text: "Повернув завдання в нечітке планування.",
  resched_failed_toast: "Не вдалося перенести",
  resched_failed_text: "Не вдалося перенести. Скажи новий час ще раз, наприклад «завтра о 10» або «пт 15:00–16:00».",
  reason_too_short: "Не вдалося перенести. Напиши коротко, чому переносиш, ще раз.",
  repeated_reschedule: "Це вже повторне перенесення. Якщо проблема не лише в часі, можна зафіксувати, що саме заважає почати.",

  followup_custom_toast: "Напиши час",
  followup_custom_prompt: "Напиши: кількість хвилин (мінімум 15), HH:MM або YYYY-MM-DD HH:MM.",
  followup_failed_toast: "Не вдалося змінити перевірку",
  followup_done: "Готово. Нагадаю {when}.",
  followup_parse_failed: "Не зрозумів час. Напиши хвилини, HH:MM або YYYY-MM-DD HH:MM.",
  snooze_reminder_toast: "Нагадаю пізніше",
  snooze_15m_button: "⏰ Через 15 хв",
  snooze_1h_button: "⏰ Через годину",

  series_paused: "Серія на паузі",
  series_cancelled: "Серію скасовано",
  series_not_found_toast: "Серію не знайдено",
  series_changed_toast: "Серія вже змінилася",

  topic_ended_toast: "Закінчено",
  topic_already_ended_toast: "Уже завершено",

  quiet_deferred_notice: "🔕 Було в тихі години, показую зараз",
  escalation_header: "🔴 Термін минув — {n}-те нагадування",
  mute_escalation_button: "🔕 Досить по цьому завданню",
  mute_escalation_toast: "Більше не нагадую по цьому завданню",

  voice_suspended: "AI-обробку для акаунта призупинено. Голосове введення недоступне.",
  ai_spend_warning: "Попередження: оцінні витрати AI цього місяця досягли ${amount}. Це лише сповіщення; AI автоматично не вимикається.",
  ai_spend_owner_notice: "IPsycho: користувач {userId} досяг AI spend warning ${amount}.",
  ops_alert: "IPsycho: черга нагадувань потребує уваги. {details}",
  voice_too_long: "Голосове надто довге або велике. Надішли запис до {minutes} хв і {mb} МБ або текст.",
  voice_openai_only: "Голосове введення зараз доступне лише з налаштованим OpenAI.",
  voice_rate_limited: "Досягнуто годинний ліміт AI. Спробуй пізніше, кнопки й нагадування працюють.",
  voice_recognizing: "🎙 Розпізнаю…",
  voice_consent_needed: "Потрібно підтвердити AI-обробку.",
  voice_unavailable: "Голосове введення зараз недоступне.",
  voice_unrecognized: "Не вдалося розпізнати мову. Спробуй записати коротше або надішли текст.",
  voice_failed: "Не вдалося обробити голосове. Спробуй надіслати його коротше або напиши текст.",
};
